import { AfterViewChecked, AfterContentChecked, ElementRef, EventEmitter } from 'angular2/core';
import { SrcService } from './src.service';
export declare class CodeblockComponent implements AfterViewChecked, AfterContentChecked {
    private _elementRef;
    private _srcService;
    contentEl: any;
    codeRenderer: any;
    constructor(_elementRef: ElementRef, _srcService: SrcService);
    ngAfterContentChecked(): void;
    ngAfterViewChecked(): void;
    content: string;
    code: string;
    lineNumbers: boolean;
    shouldDisplayLineNumbers(): boolean;
    language: string;
    theme: string;
    static THEMES: Array<string>;
    DEFAULT_THEME: string;
    DEFAULT_SHELL_THEME: string;
    src: string;
    _src: string;
    static EXTENSION_MAP: {
        'js': string;
        'ts': string;
        'html': string;
        'svg': string;
        'xml': string;
        'md': string;
        'py': string;
        'rb': string;
        'ps1': string;
        'psm1': string;
    };
    debounceTime: any;
    shell: string;
    isShell(): boolean;
    static SHELL_TYPES: Array<string>;
    prompt: string;
    outputLines: string;
    output: string;
    srcChanged: EventEmitter<string>;
    message(text: string): void;
    loading(): void;
    bind(text: string): string;
    _code: string;
    _language: string;
    _showingMessage: boolean;
    _languageSet: boolean;
    _lineNumbers: boolean;
    _theme: string;
    _changed: boolean;
    _shellType: string;
}
